version: '3' # version of docker-compose
services: # defining service/s
  web: # name of the service
    image: nodejs/hello # image named given
    build: . # directory what to build, here it is root directory
    ports:
      - "8080:8080" # defining port for our app
      - "9119:9119"